import React, { useEffect, useState } from "react";
import axios from "axios";
import toast, { Toaster } from "react-hot-toast";
import CRENavbar from "../../components/CreNavbar";
import { useAuth } from "../../context/AuthContext";
import { BASE_URL } from "../../config";

const MyGeneratedLeads = () => {
  const { authToken } = useAuth();
  const token = authToken || localStorage.getItem("token");
  const [leads, setLeads] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchGeneratedLeads = async () => {
      if (!token) return;
      setLoading(true);
      try {
        const res = await axios.get(`${BASE_URL}/api/cre/generated-leads`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        setLeads(res.data?.data || []);
      } catch (err) {
        toast.error(err.response?.data?.message || "Failed to load generated leads");
      } finally {
        setLoading(false);
      }
    };

    fetchGeneratedLeads();
  }, [token]);

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900">
      <Toaster position="top-center" />
      <CRENavbar />
      <div className="pt-20 px-4 md:px-10 max-w-7xl mx-auto pb-10">
        <div className="mb-6">
          <h1 className="text-2xl md:text-3xl font-bold text-slate-900">
            My Leads Generated
          </h1>
          <p className="text-sm text-slate-600 mt-1">
            All leads you have manually created in the system.
          </p>
        </div>

        <div className="mb-6 relative overflow-hidden rounded-2xl bg-gradient-to-br from-indigo-50 via-white to-blue-50 border border-indigo-200 shadow-lg animate-pulse">
          <div className="absolute inset-0 bg-gradient-to-r from-blue-500/5 via-indigo-500/5 to-transparent opacity-60"></div>
          <div className="relative flex items-start gap-4 p-6">
            <div className="flex-shrink-0">
              <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-indigo-600 rounded-full flex items-center justify-center shadow-md">
                <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
              </div>
            </div>
            <div className="flex-1">
              <p className="text-base font-bold text-indigo-900">Important Note</p>
              <p className="text-sm text-indigo-800 mt-1 leading-relaxed">
                Do Not Call from here. The Lead Generated by you will Automatically come to <span className="font-semibold text-indigo-900">New Leads</span> only.
              </p>
            </div>
          </div>
        </div>

        {loading ? (
          <div className="flex justify-center items-center py-16">
            <div className="animate-pulse text-slate-500">Loading leads...</div>
          </div>
        ) : leads.length === 0 ? (
          <div className="bg-white rounded-xl shadow p-6 text-center text-slate-500">
            No leads generated by you yet.
          </div>
        ) : (
          <div className="bg-white rounded-xl shadow overflow-x-auto">
            <table className="min-w-full text-sm">
              <thead className="bg-slate-100 text-slate-700">
                <tr>
                  <th className="px-4 py-2 text-left">Name</th>
                  <th className="px-4 py-2 text-left">Designation</th>
                  <th className="px-4 py-2 text-left">Company</th>
                  <th className="px-4 py-2 text-left">Industry</th>
                  <th className="px-4 py-2 text-left">Location</th>
                  <th className="px-4 py-2 text-left">Mobile</th>
                  <th className="px-4 py-2 text-left">Email</th>
                  <th className="px-4 py-2 text-left">Status</th>
                  <th className="px-4 py-2 text-left">Created At</th>
                </tr>
              </thead>
              <tbody>
                {leads.map((lead) => {
                  const company = lead.company || {};
                  const industry = company.industry || lead.industry || {};
                  const mobiles = Array.isArray(lead.mobile)
                    ? lead.mobile.join(", ")
                    : lead.mobile || "-";
                  const status = lead.status || "pending";
                  const statusColor = {
                    pending: "text-gray-600 bg-gray-100",
                    "approved for calling": "text-green-700 bg-green-100",
                    rejected: "text-red-700 bg-red-100",
                    "Non-Approved": "text-orange-700 bg-orange-100",
                  }[status] || "text-gray-600 bg-gray-100";
                  return (
                    <tr
                      key={lead._id}
                      className="border-t border-slate-100 hover:bg-slate-50"
                    >
                      <td className="px-4 py-2">{lead.name || "-"}</td>
                      <td className="px-4 py-2">{lead.designation || "-"}</td>
                      <td className="px-4 py-2">{company.CompanyName || company.name || "-"}</td>
                      <td className="px-4 py-2">{industry.name || "-"}</td>
                      <td className="px-4 py-2">{lead.location || "-"}</td>
                      <td className="px-4 py-2">{mobiles}</td>
                      <td className="px-4 py-2">{lead.email || "-"}</td>
                      <td className="px-4 py-2">
                        <span className={`px-2 py-1 rounded-full text-xs font-medium ${statusColor}`}>
                          {status}
                        </span>
                      </td>
                      <td className="px-4 py-2">
                        {lead.createdAt
                          ? new Date(lead.createdAt).toLocaleString()
                          : "-"}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
};

export default MyGeneratedLeads;
